//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Shared.Resources.IndexRes", typeof(IndexRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tecnologías en las que me especializo son principalmente la pila tecnológica de ASP NET Core..
        /// </summary>
        public static string descripcionPersonal1 {
            get {
                return ResourceManager.GetString("descripcionPersonal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis preferencias son el desarrollo de aplicaciones y sus procesos de CI/ CD..
        /// </summary>
        public static string descripcionPersonal2 {
            get {
                return ResourceManager.GetString("descripcionPersonal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas: Español e Inglés.
        /// </summary>
        public static string descripcionPersonal3 {
            get {
                return ResourceManager.GetString("descripcionPersonal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduado en la Universidad de la Rioja en Ingeniería informática y mención en ingeniería de Software..
        /// </summary>
        public static string subtituloPersonal {
            get {
                return ResourceManager.GetString("subtituloPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESARROLLADOR &amp; INGENIERO DE SOFTWARE ·.
        /// </summary>
        public static string subtituloProfesional {
            get {
                return ResourceManager.GetString("subtituloProfesional", resourceCulture);
            }
        }
    }
}
